version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - proxy
    deploy:
      labels:
        traefik.http.routers.visualizer.rule: Host('prometheus.localhost')
        traefik.http.routers.visualizer.loadbalancer.server.port: 9090
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - proxy
    deploy:
      labels:
        traefik.http.routers.visualizer.rule: Host('grafana.localhost')
        traefik.http.routers.visualizer.loadbalancer.server.port: 3000
volumes:
  prometheus-data:
  grafana-storage:
networks:
  default:
    name: monitoring
  proxy:
    external: true