version: "3.8"
services:
  app:
    image: chrisbonner/gif-collection
    ports:
      - 3000:3000
    networks:
      - default
      - monitoring
    deploy:
      replicas: 3
      update_config:
        delay: 10s
  db:
    image: mongo:4.4
    volumes:
      - gif-db:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment: 
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017 
    depends_on:
      - db
  volumes: 
    gif-db:
networks:
  monitoring:
    external: true