version: "3.8"
volumes: 
  gif-db:
services:
  app:
    image: chrisbonner/gif-collection
    networks:
      - default
      - monitoring
      - proxy
    environment:
      MONGO_CONFIG_FILE: /run/secrets/config.json
    secrets:
      - config.json
    deploy:
      replicas: 3
      update_config:
        delay: 10s
      labels:
        traefik.http.routers.app.rule: Host(`app.localhost`)
        traefik.http.services.app.loadbalancer.server.port: 3000
  db:
    image: mongo:4.4
    volumes:
      - gif-db:/data/db
  mongo-express:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - default
      - proxy
    deploy:
      labels:
        traefik.http.routers.mongo-express.rule: Host(`mongo-express.localhost`)
        traefik.http.services.mongo-express.loadbalancer.server.port: 8081
    depends_on:
      - db

secrets:
  config.json:
    external: true

networks:
  monitoring:
    external: true
  proxy:
    external: true