version: "3.8"
volumes: 
  gif-db:
services:
  app:
    image: mikesir87/gif-collection
    ports:
      - 3000:3000
    links:
      - "db:mongo"
  db:
    image: mongo:4.4
    volumes:
      - gif-db:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment: 
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017 
    depends_on:
      - db