apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage
  labels:
    type: local
spec:
  storageClassName: host
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"